export const CLIENT_EVENTS = {
    ADD_USER: "ADD_USER",
    REMOVE_USER: "REMOVE_USER",
    NEW_MESSAGE: 'NEW_MESSAGE',
    CHECK_STATUS: 'CHECK_STATUS',
    USER_OFFLINE: 'USER_OFFLINE',
    PREMIUM_ALERT: 'PREMIUM_ALERT'
};
