export const CLIENT_EVENTS = {
    ADD_USER: "ADD_USER",
    REMOVE_USER: "REMOVE_USER",
    NEW_MESSAGE: 'NEW_MESSAGE',
    START_TYPING: 'START_TYPING',
    STOP_TYPING: 'STOP_TYPING',
    SEEN_MESSAGE: 'SEEN_MESSAGE',
    CHECK_STATUS: 'CHECK_STATUS',
    PREMIUM_ALERT: 'PREMIUM_ALERT'
};
